### ISSUE TITLE
ERROR: output must be a folder (end with /) -- documentation claims file

### ISSUE THREAD

**Issue by ventz** [orcasecurity/shiftleft-container-image-action#7]
Receiving an error:

```
ERROR: output must be a folder (end with /)
```

However, per documentation it should be a file (and a file makes sense):

### Inputs

| Variable                | Example Value &nbsp; | Description &nbsp;                                                                | Type    | Required | Default |
|-------------------------|----------------------|-----------------------------------------------------------------------------------|---------|----------|---------|
| format                  | json                 | Format for displaying the results                                                 | String  | No       | cli     |
| output                  | ./results            | Output file name                                                                  | String  | No       | N/A     |

**Comment by ventz** [comment]
Issues seems to be the `-d` check here:
https://github.com/orcasecurity/shiftleft-container-image-action/blob/main/entrypoint.sh#L130

As the CLI expects a file output.

**Comment by ayala-orca** [comment]
Thank you for submitting the issue.

While the CLI supports both file and directory output, only directory output is supported by the action.
The documentation has been updated accordingly.

**Comment by ventz** [comment]
@ayala-orca Thanks.

looks like it creates a `image.json` within the folder for "format: json".

Would you mind just adding a small blurb about that in the README?

```
...
format: "json"
output: "results/"
...
```

Creates:
```
results/image.json
```

Longer term, could you add an option for a file?

I know there is SARIF, but it's still useful in order to "do something" with the results manually (ex: create GH issues for each)

**Comment by ayala-orca** [comment]
Sure! I updated the README file and opened a CRF ticket for the requested feature.
